[versions]
multiplatformMman = "1.1.0"
kotlin = "2.0.10"
kotlinxIo = "0.5.4"
kotest = "5.9.1"

dokka = "1.9.20" # https://github.com/Kotlin/dokka/releases"

[libraries]
kotest-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotlinx-io-bytestring = { module = "org.jetbrains.kotlinx:kotlinx-io-bytestring", version.ref = "kotlinxIo" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
